version: "3.8"

services:
  # start the ganache cli container
  # comment out "ganache-cli" if you use ganache desktop
  ganache-cli:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - /app/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/app/ganache_data
      - --mnemonic
      - "zebra erase plunge"
      - --networkId
      - "1337"
      - --hostname
      - "0.0.0.0"
  truffle-suite:
    container_name: truffle-suite
    build:
      context: .
      dockerfile: truffle-suite/Dockerfile
    working_dir: /opt/node_app/client
    # if developing next locally, comment out the entrypoint
    # to increase the speed of hot reloading, commment out wepback in ./client/next.config.js
    entrypoint: npm run dev
    ports:
      - 3000:3000
    volumes:
      - app-dir:/opt/node_app:rw
      # for next and caching:
      - /opt/node_app/client/.next
      - /opt/node_app/client/node_modules
    stdin_open: true # docker run -i
    tty: true # docker run -t
volumes:
  app-dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: app
